### ISSUE TITLE
pandora dev运行报错

### ISSUE THREAD

**Issue by stone-jin** [midwayjs/pandora-dashboard#14]
由于想要二次开发，所以想先把这个代码用源码跑起来。我的操作步骤如下：
```
npm install 
npm run build----》这步我看到将react代码编译完了生成到public里面的build目录了
然后查看了一下src里面代码，应该不是直接跑起来的，所以我就看到你们写着使用pandora进行跑的，

所以我用pandora dev模式跑，应该是读取profile.js里面的dev模式，打印日志也能打印到。
```

报错内容如下：
```
2018-08-28 12:35:17,569 ERROR 6357 nodejs.TypeError: Class constructor Application cannot be invoked without 'new'
    at Dashboard.WebServer [as constructor] (/Users/stone-jin/code/github/pandora-dashboard/src/WebServer.js:55:28)
    at new Dashboard (/Users/stone-jin/code/github/pandora-dashboard/src/Dashboard.js:63:42)
    at ServiceCore.instantiate (/usr/local/lib/node_modules/node/lib/node_modules/pandora/src/service/ServiceCore.ts:79:19)
    at ServiceReconciler.start (/usr/local/lib/node_modules/node/lib/node_modules/pandora/src/service/ServiceReconciler.ts:166:43)
    at <anonymous>

pid: 6357
hostname: {隐藏下}

2018-08-28 12:35:17,570 ERROR 6357 An error occurred during the start of ProcessBootstrap.
2018-08-28 12:35:17,574 INFO 6357 Process [name = worker, pid = 6357] Receive a signal SIGTERM, start to stopping, pid 6357
2018-08-28 12:35:17,591 INFO 6355 Process [name = worker, pid = 6357] Exit with code 0 and signal null
Error: Start failed! Run command [ pandora log pandora-dashboard ] to get more information

```

**Comment by stone-jin** [comment]
可能是刚刚tsc了一下，我把对应的js文件，删除后，已经成功运行。

```
Pandora.js Dashboard started, open http://127.0.0.1:9081/
2018-08-28 12:58:57,282 INFO 7742 Process [name = worker, pid = 7744] Started successfully!
** Application start successful. **

```
