### ISSUE TITLE
无法自定义接口 或者报错 pandora.service is not a function

### ISSUE THREAD

**Issue by einsqing** [midwayjs/pandora-dashboard#19]
无法自定义接口 或者报错 pandora.service is not a function

**Comment by songjian925** [comment]
同问,
pandora 2.x
Linux系统

**Comment by Swenson1992** [comment]
> 无法自定义接口 或者报错 pandora.service is not a function

pandora-dashboard 对2.x版本的pandora不适配吧,有那个sandbox docker了

**Comment by ddzyan** [comment]
我也遇到了相同的问题，请问要如何解决？操作步骤如下：
```
node -v
v10.16.0

npm -v
6.10.3

cnpm i pandora -g

cnpm i pandora-dashboard -g

pandora start --name dashboard `pandora-dashboard-dir`
[Pandora.js] Error: Command failed: /home/ddz/.nvm/versions/node/v10.16.0/bin/node  -e 'require("/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js").ProcfileReconciler.echoStructure({"appDir":"/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora-dashboard","appName":"dashboard"}, "/tmp/41e3af1b-465a-404b-8cc1-d9b295d21309"); process.exit()'
/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora-dashboard/procfile.js:7
    pandora.service('dashboard', './dist/Dashboard').process('worker');
            ^

TypeError: pandora.service is not a function
    at module.exports (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora-dashboard/procfile.js:7:13)
    at ProcfileReconciler.callProcfile (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js:81:13)
    at ProcfileReconciler.discover (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js:65:18)
    at Function.echoStructure (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js:191:28)
    at [eval]:1:133
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at evalScript (internal/bootstrap/node.js:589:27)

Error: Command failed: /home/ddz/.nvm/versions/node/v10.16.0/bin/node  -e 'require("/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js").ProcfileReconciler.echoStructure({"appDir":"/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora-dashboard","appName":"dashboard"}, "/tmp/41e3af1b-465a-404b-8cc1-d9b295d21309"); process.exit()'
/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora-dashboard/procfile.js:7
    pandora.service('dashboard', './dist/Dashboard').process('worker');
            ^

TypeError: pandora.service is not a function
    at module.exports (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora-dashboard/procfile.js:7:13)
    at ProcfileReconciler.callProcfile (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js:81:13)
    at ProcfileReconciler.discover (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js:65:18)
    at Function.echoStructure (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js:191:28)
    at [eval]:1:133
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at evalScript (internal/bootstrap/node.js:589:27)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
```
